apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-node
  template:
    metadata:
      labels:
        app: simple-node
    spec:
      containers:
        - name: simple-node
          image: kamaljuv/simple-node-k8s:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: simple-node-service
spec:
  type: LoadBalancer
  selector:
    app: simple-node
  ports:
    - port: 80
      targetPort: 3000
